### ISSUE TITLE
Investigate BDAII ROS2 driver

### ISSUE THREAD

**Issue by dcolli23** [UM-ARM-Lab/conq_python#11]
# Description

BDAII has been actively developing a ROS2 driver for Spot for a while now. When first investigating this in early 2023, the driver wasn't in a state that we could use. Now that the lab has begun the switch to ROS2 and the driver is far more developed, we should heavily consider using this. 

# Tasks

- [ ] Investigate the ROS2 driver
    - Is there any core functionality missing?
        - [ ] Ensure that arm control is fully implemented.
- [ ] Plan out how the driver would be used.
    - Would we run the driver on the laptop? On the core?
    - Would we continue development with the Python routines? 
        - It's likely that the data collection routines should stay in Python given ROS2 bandwidth complaints.
        - If we do continue Python routine development, would we need interface shims for the actual sending/receiving of messages? 
            - This could be a lot of work and confusing to people onboarding in the future.
        - Instead, it might be more reasonable to build strong walls between what works with ROS and what works with the Python API directly.
