### ISSUE TITLE
Run the tool retrieval demo

### ISSUE THREAD

**Issue by dcolli23** [UM-ARM-Lab/conq_python#6]
# Description

Running the tool retrieval demo from last semester is a good way to get familiar with the project. We should run the demo and dive into how each component works, discuss pros/cons of approaches, and brainstorm next steps for the manipulation, perception, and navigation components. 

# Tasks

- [x] ~Dylan should run this once by himself to make sure we don't have any bugs~
    - We agreed that it'd be best for the team to just hack through this since we don't want to try rerunning in Duderstadt.
- [x] Run the demo with everyone
- [x] Discuss demo results
    - What works well and shouldn't be tinkered with?
    - What works okay and may be worth rewriting to make more robust?
    - Are there any missing pieces that should be developed?
        - #3 is already highlighted as a need. This should also be implemented in a general way such that developing new behaviors/tasks is straightforward.
    - Are there any components that function okay but are a headache to work with?

**Comment by Saketspradhan** [comment]
I guess the tasks are more or less complete... can we close it?
