### ISSUE TITLE
Get familiar with current navigation stack

### ISSUE THREAD

**Issue by dcolli23** [UM-ARM-Lab/conq_python#9]
# Description

We/Boston Dynamics have already written functionality to record a map offline and navigate with that pre-recorded map online. The folk(s) working on navigation should become familiar with the stack and understand the capabilities/limits of the current stack.

# Tasks

- Look into code we have for:
    - [x] Offline map recording
    - [x] Clickmap navigation
- [x] Sit down/chat with Dylan about the process for using the navigation stack.
- [x] Generate documentation for this process.

**Comment by dcolli23** [comment]
Thanks for jumping on this, Jacob!
